/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitapbuoi2;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Admin
 */
public class Bai2_JCheckBoxMonHoc extends javax.swing.JFrame {

    public Bai2_JCheckBoxMonHoc() {
        setTitle("Demo JCheckBox Môn học lựa chọn");
        setLayout(new BorderLayout());

        JLabel titleLabel = new JLabel("Môn học yêu thích", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 16));
        add(titleLabel, BorderLayout.NORTH);

        JPanel pn = new JPanel();
        pn.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JCheckBox cb1 = new JCheckBox("Java", true);
        JCheckBox cb2 = new JCheckBox("C Sharp");
        JCheckBox cb3 = new JCheckBox("Python", true);
        JCheckBox cb4 = new JCheckBox("Ruby");
        JCheckBox cb5 = new JCheckBox("C++", true);

        pn.add(cb1);
        pn.add(cb2);
        pn.add(cb3);
        pn.add(cb4);
        pn.add(cb5);

        add(pn, BorderLayout.CENTER);

        setSize(500, 150);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> {
            new Bai2_JCheckBoxMonHoc().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
